version: '3.1'

services:
  postgres:
    image: postgres
    secrets:
      - postgresql_password_secret
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password_secret
      PGDATA: /data/postgres
    volumes:
       - ./data/postgreSqlData:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

secrets: 
  postgresql_password_secret:
    file: ./secrets/postgreSqlPassword.secret
